services:
  lanka.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=4307
    ports:
      - "4307"
  
  lanka.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:4308
      - ASPNETCORE_HTTPS_PORTS=4308
    ports:
      - "4308"