services:
  lanka.api:
    image: ${DOCKER_REGISTRY-}lankaapi
    container_name: Lanka.Api
    build:
      context: .
      dockerfile: src/API/Lanka.Api/Dockerfile
    ports:
      - "4307:4307"
    depends_on:
      lanka.queue:
        condition: service_healthy
      lanka.search:
        condition: service_healthy

  lanka.gateway:
    image: ${DOCKER_REGISTRY-}lankagateway
    container_name: Lanka.Gateway
    build:
      context: .
      dockerfile: src/Api/Lanka.Gateway/Dockerfile
    ports:
      - "4308:4308"
    depends_on:
      - lanka.api
  
  lanka.database:
    image: postgres:latest
    container_name: Lanka.Database
    environment:
      - POSTGRES_DB=lanka
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  lanka.seq:
    image: datalust/seq:latest
    container_name: Lanka.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5431:5431"
      - "8081:80"
  
  lanka.redis:
    image: redis:latest
    container_name: Lanka.Redis
    restart: always
    ports:
      - "6379:6379"
  
  lanka.identity:
    image: quay.io/keycloak/keycloak:latest
    container_name: Lanka.Identity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - "18080:8080"
      - "9000:9000"
  
  lanka.jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: Lanka.Jaeger
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
  
  lanka.queue:
    image: rabbitmq:management-alpine
    container_name: Lanka.Queue
    hostname: lanka-queue
    volumes:
      - ./.containers/queue/data/:/var/lib/rabbitmq
      - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"

  lanka.mongo:
    image: mongo:latest
    container_name: Lanka.Mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./.containers/mongo:/data/db
    ports:
      - "27017:27017"
  
  lanka.search:
    image: elasticsearch:9.1.3
    container_name: Lanka.Search
    command: >
      /bin/bash -c "
        bin/elasticsearch-plugin install analysis-icu --batch;
        /usr/local/bin/docker-entrypoint.sh"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    volumes:
      - ./.containers/search/data:/usr/share/elasticsearch/data
      - ./.containers/search/logs:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
  
  lanka.kibana:
    image: kibana:9.1.3
    container_name: Lanka.Kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://lanka.search:9200
    ports:
      - "5601:5601"
    depends_on:
      - lanka.search