// <auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Lanka.Modules.Users.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddChatPermissions : Migration
    {
        private static readonly string[] RolePermissionColumns =
        [
            "permission_code",
            "role_name"
        ];

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                schema: "users",
                table: "permissions",
                column: "code",
                values: new object[]
                {
                    "chat:read",
                    "chat:write"
                });

            migrationBuilder.InsertData(
                schema: "users",
                table: "role_permissions",
                columns: RolePermissionColumns,
                values: new object[,]
                {
                    { "chat:read", "Administrator" },
                    { "chat:read", "Member" },
                    { "chat:write", "Administrator" },
                    { "chat:write", "Member" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                schema: "users",
                table: "role_permissions",
                keyColumns: RolePermissionColumns,
                keyValues: new object[] { "chat:read", "Administrator" });

            migrationBuilder.DeleteData(
                schema: "users",
                table: "role_permissions",
                keyColumns: RolePermissionColumns,
                keyValues: new object[] { "chat:read", "Member" });

            migrationBuilder.DeleteData(
                schema: "users",
                table: "role_permissions",
                keyColumns: RolePermissionColumns,
                keyValues: new object[] { "chat:write", "Administrator" });

            migrationBuilder.DeleteData(
                schema: "users",
                table: "role_permissions",
                keyColumns: RolePermissionColumns,
                keyValues: new object[] { "chat:write", "Member" });

            migrationBuilder.DeleteData(
                schema: "users",
                table: "permissions",
                keyColumn: "code",
                keyValue: "chat:read");

            migrationBuilder.DeleteData(
                schema: "users",
                table: "permissions",
                keyColumn: "code",
                keyValue: "chat:write");
        }
    }
}
