// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lanka.Modules.Analytics.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class RemoveCategory : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_accounts_categories_category_name",
                schema: "analytics",
                table: "accounts");

            migrationBuilder.DropTable(
                name: "categories",
                schema: "analytics");

            migrationBuilder.DropIndex(
                name: "ix_accounts_category_name",
                schema: "analytics",
                table: "accounts");

            migrationBuilder.DropColumn(
                name: "category_name",
                schema: "analytics",
                table: "accounts");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "category_name",
                schema: "analytics",
                table: "accounts",
                type: "character varying(100)",
                nullable: false,
                defaultValue: "None");

            migrationBuilder.CreateTable(
                name: "categories",
                schema: "analytics",
                columns: table => new
                {
                    name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_categories", x => x.name);
                });

            migrationBuilder.InsertData(
                schema: "analytics",
                table: "categories",
                column: "name",
                values: new object[]
                {
                    "Animals",
                    "Art",
                    "Automobiles",
                    "Clothing and Footwear",
                    "Comedy",
                    "Cooking and Food",
                    "Cryptocurrency",
                    "DIY and Crafts",
                    "Education",
                    "Entrepreneurship",
                    "Environment",
                    "Fashion and Style",
                    "Finance",
                    "Fitness",
                    "Gaming",
                    "Health and Wellness",
                    "History",
                    "Home Decor",
                    "Horticulture",
                    "Legal Advice",
                    "Literature",
                    "Marketing",
                    "Mental Health",
                    "Movies and TV",
                    "Music",
                    "News",
                    "None",
                    "Parenting",
                    "Personal Development",
                    "Photography",
                    "Politics",
                    "Real Estate",
                    "Relationships",
                    "Religion and Spirituality",
                    "Science",
                    "Self Improvement",
                    "Social Media",
                    "Sports",
                    "Technology",
                    "Travel"
                });

            migrationBuilder.CreateIndex(
                name: "ix_accounts_category_name",
                schema: "analytics",
                table: "accounts",
                column: "category_name");

            migrationBuilder.AddForeignKey(
                name: "fk_accounts_categories_category_name",
                schema: "analytics",
                table: "accounts",
                column: "category_name",
                principalSchema: "analytics",
                principalTable: "categories",
                principalColumn: "name",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
