// <auto-generated />
using System;
using Lanka.Modules.Analytics.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lanka.Modules.Analytics.Infrastructure.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20251209101106_RemoveCategory")]
    partial class RemoveCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("analytics")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lanka.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "analytics");
                });

            modelBuilder.Entity("Lanka.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "analytics");
                });

            modelBuilder.Entity("Lanka.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "analytics");
                });

            modelBuilder.Entity("Lanka.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "analytics");
                });

            modelBuilder.Entity("Lanka.Modules.Analytics.Domain.InstagramAccounts.InstagramAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdvertisementAccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("advertisement_account_id");

                    b.Property<string>("FacebookPageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("facebook_page_id");

                    b.Property<DateTimeOffset?>("LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.ToTable("accounts", "analytics");
                });

            modelBuilder.Entity("Lanka.Modules.Analytics.Domain.Tokens.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<Guid>("InstagramAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("instagram_account_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_tokens");

                    b.HasIndex("InstagramAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_tokens_instagram_account_id");

                    b.ToTable("tokens", "analytics");
                });

            modelBuilder.Entity("Lanka.Modules.Analytics.Domain.InstagramAccounts.InstagramAccount", b =>
                {
                    b.OwnsOne("Lanka.Modules.Analytics.Domain.InstagramAccounts.Metadatas.Metadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("InstagramAccountId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("FollowersCount")
                                .HasColumnType("integer")
                                .HasColumnName("metadata_followers_count");

                            b1.Property<string>("Id")
                                .HasColumnType("text")
                                .HasColumnName("metadata_id");

                            b1.Property<long>("IgId")
                                .HasColumnType("bigint")
                                .HasColumnName("metadata_ig_id");

                            b1.Property<int>("MediaCount")
                                .HasColumnType("integer")
                                .HasColumnName("metadata_media_count");

                            b1.Property<string>("UserName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("metadata_user_name");

                            b1.HasKey("InstagramAccountId");

                            b1.ToTable("accounts", "analytics");

                            b1.WithOwner()
                                .HasForeignKey("InstagramAccountId")
                                .HasConstraintName("fk_accounts_accounts_id");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("Lanka.Modules.Analytics.Domain.Tokens.Token", b =>
                {
                    b.HasOne("Lanka.Modules.Analytics.Domain.InstagramAccounts.InstagramAccount", "InstagramAccount")
                        .WithOne("Token")
                        .HasForeignKey("Lanka.Modules.Analytics.Domain.Tokens.Token", "InstagramAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tokens_accounts_instagram_account_id");

                    b.Navigation("InstagramAccount");
                });

            modelBuilder.Entity("Lanka.Modules.Analytics.Domain.InstagramAccounts.InstagramAccount", b =>
                {
                    b.Navigation("Token");
                });
#pragma warning restore 612, 618
        }
    }
}
