// <auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lanka.Modules.Campaigns.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class ResolvePriceAmountColumnAbsence : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<decimal>(
                name: "price_amount",
                schema: "campaigns",
                table: "offers",
                type: "numeric",
                nullable: false,
                defaultValue: 0m);

            migrationBuilder.AddColumn<decimal>(
                name: "price_amount",
                schema: "campaigns",
                table: "campaigns",
                type: "numeric",
                nullable: false,
                defaultValue: 0m);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "price_amount",
                schema: "campaigns",
                table: "offers");

            migrationBuilder.DropColumn(
                name: "price_amount",
                schema: "campaigns",
                table: "campaigns");
        }
    }
}
