// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lanka.Modules.Campaigns.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddCategory : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "category_name",
                schema: "campaigns",
                table: "bloggers",
                type: "character varying(100)",
                nullable: false,
                defaultValue: "None");

            migrationBuilder.CreateTable(
                name: "categories",
                schema: "campaigns",
                columns: table => new
                {
                    name = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_categories", x => x.name);
                });

            migrationBuilder.InsertData(
                schema: "campaigns",
                table: "categories",
                column: "name",
                values: new object[]
                {
                    "Animals",
                    "Art",
                    "Automobiles",
                    "Clothing and Footwear",
                    "Comedy",
                    "Cooking and Food",
                    "Cryptocurrency",
                    "DIY and Crafts",
                    "Education",
                    "Entrepreneurship",
                    "Environment",
                    "Fashion and Style",
                    "Finance",
                    "Fitness",
                    "Gaming",
                    "Health and Wellness",
                    "History",
                    "Home Decor",
                    "Horticulture",
                    "Legal Advice",
                    "Literature",
                    "Marketing",
                    "Mental Health",
                    "Movies and TV",
                    "Music",
                    "News",
                    "None",
                    "Parenting",
                    "Personal Development",
                    "Photography",
                    "Politics",
                    "Real Estate",
                    "Relationships",
                    "Religion and Spirituality",
                    "Science",
                    "Self Improvement",
                    "Social Media",
                    "Sports",
                    "Technology",
                    "Travel"
                });

            migrationBuilder.CreateIndex(
                name: "ix_bloggers_category_name",
                schema: "campaigns",
                table: "bloggers",
                column: "category_name");

            migrationBuilder.AddForeignKey(
                name: "fk_bloggers_categories_category_name",
                schema: "campaigns",
                table: "bloggers",
                column: "category_name",
                principalSchema: "campaigns",
                principalTable: "categories",
                principalColumn: "name",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_bloggers_categories_category_name",
                schema: "campaigns",
                table: "bloggers");

            migrationBuilder.DropTable(
                name: "categories",
                schema: "campaigns");

            migrationBuilder.DropIndex(
                name: "ix_bloggers_category_name",
                schema: "campaigns",
                table: "bloggers");

            migrationBuilder.DropColumn(
                name: "category_name",
                schema: "campaigns",
                table: "bloggers");
        }
    }
}
