// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lanka.Modules.Campaigns.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddInstagramMetadata : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "instagram_metadata_followers_count",
                schema: "campaigns",
                table: "bloggers",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "instagram_metadata_media_count",
                schema: "campaigns",
                table: "bloggers",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "instagram_metadata_username",
                schema: "campaigns",
                table: "bloggers",
                type: "text",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "instagram_metadata_followers_count",
                schema: "campaigns",
                table: "bloggers");

            migrationBuilder.DropColumn(
                name: "instagram_metadata_media_count",
                schema: "campaigns",
                table: "bloggers");

            migrationBuilder.DropColumn(
                name: "instagram_metadata_username",
                schema: "campaigns",
                table: "bloggers");
        }
    }
}
