// <auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Lanka.Modules.Campaigns.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddChatThreads : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS campaigns.chat_threads (
                    id uuid NOT NULL,
                    participant_a_id uuid NOT NULL,
                    participant_b_id uuid NOT NULL,
                    campaign_id uuid NULL,
                    offer_id uuid NULL,
                    created_at_utc timestamp with time zone NOT NULL,
                    updated_at_utc timestamp with time zone NOT NULL,
                    CONSTRAINT pk_chat_threads PRIMARY KEY (id)
                );

                DO $$
                BEGIN
                    IF to_regclass('campaigns.chat_messages') IS NULL THEN
                        CREATE TABLE campaigns.chat_messages (
                            id uuid NOT NULL,
                            thread_id uuid NOT NULL,
                            sender_blogger_id uuid NULL,
                            content character varying(4000) NOT NULL,
                            is_system boolean NOT NULL,
                            is_deleted boolean NOT NULL,
                            edited_at_utc timestamp with time zone NULL,
                            read_at_utc timestamp with time zone NULL,
                            created_at_utc timestamp with time zone NOT NULL,
                            CONSTRAINT pk_chat_messages PRIMARY KEY (id)
                        );
                    ELSIF EXISTS (
                        SELECT 1
                        FROM information_schema.columns
                        WHERE table_schema = 'campaigns'
                          AND table_name = 'chat_messages'
                          AND column_name = 'campaign_id'
                    ) THEN
                        ALTER TABLE campaigns.chat_messages
                            DROP CONSTRAINT IF EXISTS fk_chat_messages_campaigns_campaign_id;

                        INSERT INTO campaigns.chat_threads (
                            id,
                            participant_a_id,
                            participant_b_id,
                            campaign_id,
                            offer_id,
                            created_at_utc,
                            updated_at_utc
                        )
                        SELECT
                            c.id,
                            c.client_id,
                            c.creator_id,
                            c.id,
                            NULL,
                            COALESCE(MIN(cm.created_at_utc), now()),
                            COALESCE(MAX(cm.created_at_utc), now())
                        FROM campaigns.chat_messages cm
                        INNER JOIN campaigns.campaigns c ON c.id = cm.campaign_id
                        GROUP BY c.id, c.client_id, c.creator_id
                        ON CONFLICT (id) DO NOTHING;

                        ALTER TABLE campaigns.chat_messages
                            RENAME COLUMN campaign_id TO thread_id;

                        ALTER INDEX IF EXISTS campaigns.ix_chat_messages_campaign_id_created_at_utc
                            RENAME TO ix_chat_messages_thread_id_created_at_utc;
                    END IF;

                    IF NOT EXISTS (
                        SELECT 1
                        FROM pg_constraint
                        WHERE conname = 'fk_chat_messages_chat_threads_thread_id'
                    ) THEN
                        ALTER TABLE campaigns.chat_messages
                            ADD CONSTRAINT fk_chat_messages_chat_threads_thread_id
                            FOREIGN KEY (thread_id)
                            REFERENCES campaigns.chat_threads(id)
                            ON DELETE CASCADE;
                    END IF;
                END $$;

                CREATE INDEX IF NOT EXISTS ix_chat_messages_thread_id_created_at_utc
                    ON campaigns.chat_messages (thread_id ASC, created_at_utc DESC);

                CREATE INDEX IF NOT EXISTS ix_chat_threads_campaign_id
                    ON campaigns.chat_threads (campaign_id);

                CREATE INDEX IF NOT EXISTS ix_chat_threads_offer_id
                    ON campaigns.chat_threads (offer_id);

                CREATE INDEX IF NOT EXISTS ix_chat_threads_participant_a_id
                    ON campaigns.chat_threads (participant_a_id);

                CREATE INDEX IF NOT EXISTS ix_chat_threads_participant_b_id
                    ON campaigns.chat_threads (participant_b_id);
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "chat_messages",
                schema: "campaigns");

            migrationBuilder.DropTable(
                name: "chat_threads",
                schema: "campaigns");
        }
    }
}
